name: Test Env Inputs
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

env:
  GREETING: "Hello ${{ inputs.name }}"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.GREETING }}"
