name: Test Secrets
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      my_secret:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ inputs.name }}"
